use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=assets/zstd_dictionary");

    let out_dir = env::var("OUT_DIR").unwrap();
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let dict_path = PathBuf::from(crate_dir).join("assets/zstd_dictionary");

    let dict_bytes = fs::read(&dict_path).expect("Failed to read dictionary");
    let rust_code = format!(
        "// Auto-generated by build.rs\npub static ZSTD_DICTIONARY: &[u8] = &[{}];\n",
        dict_bytes.iter().map(|b| b.to_string()).collect::<Vec<_>>().join(", ")
    );

    let out_path = PathBuf::from(&out_dir).join("zstd_dict.rs");
    fs::write(&out_path, rust_code).expect("Failed to write zstd_dict.rs");

    println!("cargo:rustc-env=ZSTD_DICT_RS={}", out_path.display());
}
