use std::env;
use std::fs;
use std::path::PathBuf;

const ZSTD_DICT_URL: &str =
    "https://raw.githubusercontent.com/bluesky-social/jetstream/main/pkg/models/zstd_dictionary";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dict_path = PathBuf::from(&out_dir).join("zstd_dictionary");

    if !dict_path.exists() {
        println!("cargo:warning=Fetching zstd dictionary from Jetstream repo...");

        match reqwest::blocking::get(ZSTD_DICT_URL) {
            Ok(response) => match response.status().is_success() {
                true => match response.bytes() {
                    Ok(bytes) => {
                        let size = bytes.len();
                        fs::write(&dict_path, bytes).expect("Failed to write zstd dictionary");
                        println!("cargo:warning=Successfully fetched zstd dictionary ({} bytes)", size);
                    }
                    Err(e) => panic!("Failed to read zstd dictionary bytes: {}", e),
                },
                false => panic!("Failed to fetch zstd dictionary: HTTP {}", response.status()),
            },
            Err(e) => panic!("Failed to download zstd dictionary: {}", e),
        }
    }

    let dict_bytes = fs::read(&dict_path).expect("Failed to read dictionary");
    let rust_code = format!(
        "// Auto-generated by build.rs\npub static ZSTD_DICTIONARY: &[u8] = &[{}];\n",
        dict_bytes.iter().map(|b| b.to_string()).collect::<Vec<_>>().join(", ")
    );

    let out_path = PathBuf::from(&out_dir).join("zstd_dict.rs");
    fs::write(&out_path, rust_code).expect("Failed to write zstd_dict.rs");

    println!("cargo:rustc-env=ZSTD_DICT_RS={}", out_path.display());
}
